version: "3.9"

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      bash -c "
      rasa run actions -vv > /app/run_actions_logs.txt & /workspace/.devcontainer/scripts/launch-rasa-server.py
      "
    volumes:
      - .:/workspace:cached
