version: "3.9"

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      bash -c "
      RAPPO_ENV=${RAPPO_ENV} rasa run actions -vv > /app/run_actions_logs.txt & NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN} NGROK_REGION=${NGROK_REGION} python /workspace/.devcontainer/scripts/launch-rasa-server.py run -vv --log-file /app/server_logs.txt
      "
    environment: 
      HOME: "/tmp"
    volumes:
      - .:/workspace:cached
